### ISSUE TITLE
Bug: Maven 4.0.0-alpha-1 version block release

### ISSUE THREAD

**Issue by ahmadshalabi** [sdkman/sdkman-cli#1033] opened 2022-01-09 21:15 UTC
**Bug report**
When the migration tool tries to validate change with id (009-add_maven_4.0.0-alpha-1), it fails since the version is no longer hosted by apache maven.

**Comment by marc0der** [comment] 2022-01-09 21:34
This is not a bug on the CLI so closing this issue.

**Closed by marc0der** 2022-01-09 21:34 UTC
Labels: bug
