### ISSUE TITLE
Can't install sdkman when using curl -O

### ISSUE THREAD

**Issue by tabrezm** [sdkman/sdkman-cli#1302] opened 2024-07-09 03:06 UTC
**Bug report**
Install command on homepage doesn't work when `curl` is aliased to `curl -O`:
```
$ curl -s "https://get.sdkman.io" | bash
```
Due to `-s`, it returns silently with no error. Disabling alias works. This is the error when running without `-s`:
```
➜ curl -O "https://get.sdkman.io" | bash
curl: Remote file name has no length
curl: (23) Failed writing received data to disk/application
```

I disabled the alias for install and re-installed it after install, but it looks like `sdk` itself can't run either:
```
➜ sdk   
==== INTERNET NOT REACHABLE! ===================================================

 Some functionality is disabled or only partially available.
 If this persists, please enable the offline mode:

   $ sdk offline

================================================================================
```

**To reproduce**
1. `alias curl="curl -OJ"`
2. Attempt to install or run sdkman

**System info**
macOS
zsh 5.9 (x86_64-apple-darwin23.0)
curl 8.6.0 (x86_64-apple-darwin23.0) libcurl/8.6.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.12 nghttp2/1.61.0

**Comment by sdavids** [comment] 2024-08-06 09:57
This could be fixed by adding `unalias -a` to the appropriate scripts.

*But* I strongly suggest you do not alias fundamental Unix utilities—thereby possibly breaking a lot of scripts.

`alias curlo="curl -OJ"` would be one option on your side.

Depending on your use case you might want to edit the [default curl config file](https://everything.curl.dev/cmdline/configfile.html#default-config-file).

**Comment by marc0der** [comment] 2024-08-06 12:43
This is not a bug. We assume the underlying commands to be unaltered. If you want an alias for this behaviour, I suggest having it as a different name, perhaps something like `curlo` or similar.

**Closed by marc0der** 2024-08-06 12:43 UTC
Labels: bug
