### ISSUE TITLE
Remote version corrupt when proxy blocks version API call

### ISSUE THREAD

**Issue by kenliu** [sdkman/sdkman-cli#253] opened 2013-12-11 14:16 UTC
I was running my laptop behind a proxy yesterday (my tethered Android connection was being blocked by T-Mobile) and GVM got into a bad state during the version check. Now today it keeps displaying the same message even though I am connected to the Internet properly.

```
Last login: Tue Dec 10 16:25:53 on ttys012
A new version of GVM is available...

The current version is The document has moved, but you have 1.3.12.

Would you like to upgrade now? (Y/n)n
Not upgrading now...
```

**Comment by hho** [comment] 2015-05-26 09:03
I'm not behind a proxy, but `gvm` wants to update itself every day anyway:

```
hho@hho-pc: ~
➜ gvm o
All candidates are up-to-date


ATTENTION: A new version of GVM is available...

The current version is , but you have 2.4.1.

Would you like to upgrade now? (Y/n)n
Not upgrading today...

hho@hho-pc: ~
➜
```

(and yes, there is nothing but a single space between "is" and the comma)

**Comment by marcoVermeulen** [comment] 2015-05-27 22:50
I have seen this upgrade to blank version too, but can't seem to replicate it again of late.

**Comment by hho** [comment] 2015-06-17 09:58
I've tried to debug it (via `bash -xv`) and it seems the problem is an empty `GVM_REMOTE_VERSION` variable. I grepped through the code and that variable is set in `gvm-init.sh`, but never exported: https://github.com/gvmtool/gvm-cli/blob/2.4.1/src/main/bash/gvm-init.sh#L187-L200

However, there already seems to be a more complicated pull request (#306) in progress, dealing with the empty version number. Maybe that fixes this issue as well?

**Comment by marcoVermeulen** [comment] 2015-06-17 11:36
We seem to be discussing 2 separate things here. The first is an invalid response (and how we interpret that) from the api. The second is a missing version number (`GVM_REMOTE_VERSION`) prompting a user to upgrade even if they are already on the latest version. This later is issue #317 and is currently being worked on.

**Comment by marc0der** [comment] 2016-07-05 15:53
AFAIK this is resolved. Can this be confirmed so I can close the issue?

**Comment by marc0der** [comment] 2016-07-22 18:49
No response so closing issue.

**Closed by marc0der** 2016-07-22 18:49 UTC
