### ISSUE TITLE
prevent sdkman from checking for new version on startup

### ISSUE THREAD

**Issue by rbartl** [sdkman/sdkman-cli#586] opened 2017-06-06 13:09 UTC
as mentioned in "disable auto upgrade check #455"  it would be nice to disable the version check on startup (which is cached but nonetheless is annoying in the wrong moment)
sdkman_auto_selfupdate variable does not help.

as far as i've seen in sdkman-init.sh line 121 (current stable) the version is checked if the cache is older than "+$((60*24)))"  and always if beta is selected.

BR, RB.

**Comment by marc0der** [comment] 2017-06-08 18:46
Sdkman needs to be online to work. We don't do a version check every time, but do a tiny heartbeat call to the broadcast api to determine if we are online. If we aren't online, we degrade the user experience to a subset of functionality. This is not going to change anytime soon. 

If you are having issues, I suggest tweaks to the curl settings in the etc/conf file.

**Comment by rbartl** [comment] 2017-06-08 20:11
i just removed the block after "# determine if up to date" in sdkman-init.sh  - that fixed any timeouts when starting a shell and having flacky internet.

**Comment by marc0der** [comment] 2017-06-08 20:20
So this code is all tested in the following [spec](https://github.com/sdkman/sdkman-cli/blob/master/src/test/groovy/sdkman/specs/VersionCacheBootstrapSpec.groovy). Has something been overlooked that it's making more calls than it should?

**Comment by ilgarm** [comment] 2017-08-25 12:33
Nice tool, thank you! But this is annoying indeed, even with internet connectivity my shell session startup is delayed at least once per day. Not sure why this is default behaviour.

**Comment by marc0der** [comment] 2017-08-26 23:12
@ilgarm If you are experiencing issues due to slow internet connection, curl timeouts can be configured as described on the [Usage Page](http://sdkman.io/usage.html#config) of our website.

**Comment by unlimitedsola** [comment] 2017-10-25 06:40
pretty annoying +1, especially some programs may create a new bash and have to block to wait the update check when in poor network environment

**Comment by marc0der** [comment] 2017-10-25 21:48
@unlimitedsola as before, you can tweak the timeouts in the `.sdkman/etc/config` file to make the it timeout shorter. Everything is fully configurable.

We will always be doing this heartbeat as this is vital for sdkman to work (it depends on the internet to function properly). Closing this as it's not an issue.

**Closed by marc0der** 2017-10-25 21:48 UTC

**Comment by unlimitedsola** [comment] 2017-10-28 00:49
@marc0der even though sdkman depends on internet, why don't we only check internet connectivity as needed(when executing command/function)?
It's rare to see a program that make a operation blocks bash launching, and this will also greatly slow down other programs which uses bash (i.e. IDEs)

**Comment by foobra** [comment] 2017-10-30 08:03
Blocking every termial's startup is stupid, no matter what reason.

**Comment by marc0der** [comment] 2017-10-30 08:09
You're always free to dive into the source and raise a PR.

**Comment by marc0der** [comment] 2017-11-02 11:46
@foobra BTW, we don't block every terminal. This check only happens once a day. We could potentially relax this even further.

**Comment by foobra** [comment] 2017-11-03 07:16
@marc0der Sorry for the rude words. The problem is in China, the [GreatFireWall](https://en.wikipedia.org/wiki/Great_Firewall) block sdkman's url. So everyday not even one update request success. sdkman will repeat request update  in new terminal opening and blocking, it's a nightmare.

So my suggestion is turn off auto update by default, just like homebrew. Give the choice to the users, they are smart to know how to update b/c they choose sdkman 🍻

**Comment by netroby** [comment] 2017-11-16 01:15
+1 disable sdkman update ,or our bash/zsh startup will slow, very slow

**Comment by texasbruce** [comment] 2017-11-21 03:33
You can execute `sdk offline enable` to go offline in a live shell.

To persist and boost shell startup time, adding `export SDKMAN_OFFLINE_MODE="true"` to your shell rc file (before the sdkman source statement) seems to do the trick.

**Comment by texasbruce** [comment] 2017-11-21 03:55
If the offline mode variable SDKMAN_OFFLINE_MODE is set to true, shouldn't it NOT try to connect at all (both at startup and executing command)? I can submit a PR if you agree with this.

**Comment by marc0der** [comment] 2017-11-21 13:15
Nope, that's an internal environment variable used by sdkman. sdkman is
configured by the configurations in `~/.sdkman/etc/config`, however
configuring sdkman to be offline permanently makes no sense at all.

**Comment by unlimitedsola** [comment] 2017-11-21 15:47
Well, lets remove offline mode then because it makes no sense at all. 💢

**Comment by marc0der** [comment] 2017-11-21 21:50
It certainly does. sdkman degrades it's functionality gracefully when it
can't reach the internet (or if you do an `sdk offline enable`). It allows
you to still switch versions etc, although it doesn't allow you to do
anything that requires internet access (such as install new
versions).You're welcome to read the specification here:
https://github.com/sdkman/sdkman-cli/blob/master/src/test/cucumber/offline_mode.feature

Offline mode allows you to work when you're on an airplane for instance (in
it's earliest iterations we called it airplane mode). I and many others use
it all the time and it works great. Offline mode won't be going anytime
soon.

**Comment by rbartl** [comment] 2017-11-21 22:03
my pragmatic change for this was to just remove/disable the update check and candidate fetching.

- removed "(find "$SDKMAN_VERSION_FILE" -mmin +$((60*24)))" in the update block
- removed "$(find "$SDKMAN_CANDIDATES_CACHE" -mmin +$((60*24)))" in the candidate update block (i just put it back again if i want fresh candidates)
i really do not care for version/candidate checks when i start my terminal.

if its ok i would create a pull request and make this configurable - currently im just changing it again when i update it.

**Comment by marc0der** [comment] 2017-11-21 22:05
I'm currently working on changes to prevent any calls out on shell
initialisation. It will be possible to refresh the candidate cache by a new
`sdk update` command, similar to how apt-get works. I hope to roll this out
within the next week. However, offline mode will remain a feature.

**Comment by texasbruce** [comment] 2017-11-22 10:16
That sounds great!

**Comment by unlimitedsola** [comment] 2017-11-22 11:15
Finally made you change your mind 👍
