### ISSUE TITLE
Bug: Cannot install gradle 7.2 on Ubuntu LTS 20.04 with SDKMAN 5.12.3

### ISSUE THREAD

**Issue by santfirax** [sdkman/sdkman-cli#963] opened 2021-09-04 01:48 UTC
**Bug report**

**To reproduce**
I followed this guide on the website to install SDKMAN on Ubuntu
https://sdkman.io/install
then sdk install gradle 7.2 and it throws the following error
Downloading: gradle 7.2

In progress...

Warning: Failed to create the file /home/smolano/.sdkman/tmp/gradle-7.2.bin:    
Warning: Permission denied
curl: (23) Failure writing output to destination

mv: cannot stat '/home/smolano/.sdkman/tmp/gradle-7.2.bin': No such file or directory

Then I tried running it with sudo and it shows this error
udo: sdk: command not found
**System info**

**Comment by marc0der** [comment] 2021-09-04 07:48
Hi @santfirax, it sounds like a permissions problem to me. This sort of thing usually happens when you run SDKMAN with sudo (which you should absolutely never do). You now have files and folders in your home directory that belong to the root user.

I'd be happy to help you get this resolved, although I'm closing this issue because it's not a bug. Please reach out on slack where one of us would be more than happy to help you get it resolved.

**Closed by marc0der** 2021-09-04 07:48 UTC
Labels: bug
