### ISSUE TITLE
Install java 8 fails on cygwin in some cases

### ISSUE THREAD

**Issue by jbuhacoff** [sdkman/sdkman-cli#520] opened 2017-01-07 10:15 UTC
On Cygwin, tried `sdk install java` and got following output:

```
$ sdk install java

Oracle requires that you agree with the Oracle Binary Code License Agreement
prior to installation. The license agreement can be found at:

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

Do you agree to the terms of this agreement? (Y/n): Y


Downloading: java 8u111

In progress...

######################################################################## 100.0%

Repackaging java 8u111...
-bash: /home/Jonathan/.sdkman/tmp/mbgywYdNTdwToa040cg3Azu3oUSUBGsp.bin: Device or resource busy
mv: cannot stat '/cygdrive/c/temp/jdk': No such file or directory

zip error: Nothing to do! (try: zip -qr /home/Jonathan/.sdkman/tmp/mbgywYdNTdwToa040cg3Azu3oUSUBGsp.zip . -i .)

Done repackaging...
mv: cannot stat '/home/Jonathan/.sdkman/tmp/mbgywYdNTdwToa040cg3Azu3oUSUBGsp.zip': No such file or directory
unzip:  cannot find or open /home/Jonathan/.sdkman/archives/java-8u111.zip, /home/Jonathan/.sdkman/archives/java-8u111.zip.zip or /home/Jonathan/.sdkman/archives/java-8u111.zip.ZIP.
rm: cannot remove '/home/Jonathan/.sdkman/archives/java-8u111.zip': No such file or directory

Stop! The archive was corrupt and has been removed! Please try installing again.
```

To check device or resource busy, I ran handle command for windows: 

```
C:\>handle mbgywYdNTdwToa040cg3Azu3oUSUBGsp.bin

Nthandle v4.1 - Handle viewer
Copyright (C) 1997-2016 Mark Russinovich
Sysinternals - www.sysinternals.com

bash.exe           pid: 8008   type: File           3D0: C:\Users\Jonathan\.sdkman\tmp\mbgywYdNTdwToa040cg3Azu3oUSUBGsp.bin
```

And then I ran `ps` within Cygwin:

```
$ ps
      PID    PPID    PGID     WINPID   TTY         UID    STIME COMMAND
     1948   13268    1948       8008  pty3      197609 19:57:39 /usr/bin/bash
     7532   12708    7532       8256  pty2      197609 02:13:00 /usr/bin/ps
     1044    1164    1044      15392  pty0      197609 19:28:45 /usr/bin/bash
    13268       1   13268      13268  ?         197609 19:57:39 /usr/bin/mintty
    14852       1   14852      14852  ?         197609 19:51:14 /usr/bin/mintty
    12708   14852   12708       4204  pty2      197609 19:51:14 /usr/bin/bash
     1164       1    1164       1164  ?         197609 19:28:45 /usr/bin/mintty
```

**Comment by marc0der** [comment] 2017-01-07 23:13
Thanks for reporting this issue. So far we have had many successful installations of Java on cygwin, so it might only be an anomaly on your environment.

Lets keep this open in case others are also seeing this.

**Comment by ecirtap** [comment] 2017-01-08 14:41
Hello, thanks for leaving this issue opened; I encountered the same problem:

```
$ sdk install java

Oracle requires that you agree with the Oracle Binary Code License Agreement
prior to installation. The license agreement can be found at:

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

Do you agree to the terms of this agreement? (Y/n):


Downloading: java 8u111

In progress...

######################################################################## 100,0%

Repackaging java 8u111...
-bash: /home/patri/.sdkman/tmp/eQ6x6SakpNulzdTag1yvfV0HbG7DrldS.bin: Permission denied
mv: impossible d'évaluer '/cygdrive/c/temp/jdk': No such file or directory

zip error: Nothing to do! (try: zip -qr /home/patri/.sdkman/tmp/eQ6x6SakpNulzdTag1yvfV0HbG7DrldS.zip . -i .)

Done repackaging...
mv: impossible d'évaluer '/home/patri/.sdkman/tmp/eQ6x6SakpNulzdTag1yvfV0HbG7DrldS.zip': No such file or directory
unzip:  cannot find or open /home/patri/.sdkman/archives/java-8u111.zip, /home/patri/.sdkman/archives/java-8u111.zip.zip or /home/patri/.sdkman/archives/java-8u111.zip.ZIP.
rm: impossible de supprimer '/home/patri/.sdkman/archives/java-8u111.zip': No such file or directory

Stop! The archive was corrupt and has been removed! Please try installing again.
```

Win10 pro, cygwin64, SDKMAN 5.5.2+183

**Comment by ecirtap** [comment] 2017-01-08 15:16
I think it is due to UAC (enabled on my box); a 740 error is returned by strace when it is used to run the downloaded binary (more informative than the permission denied error returned by bash).

Workaround i used: run the same command, but in the context of a Cygwin Windows opened "as Administrator".

**Comment by marc0der** [comment] 2017-01-08 16:04
I'm not a cygwin expert, but won't that mess up the permissions under you sdkman folder?

**Comment by ecirtap** [comment] 2017-01-08 16:30
Neither do I ... who is an expert of something nowadays :-)

I have just checked that all files under .sdkman are mines (`find .sdkman \! -user patri` returns no result). The same stands for my whole cygwin account.

I also installed other SDKMAN packages after that (ant, maven, groovyserv) using a normal cygwin window, and it worked.

When cygwin is run "As administrator", it happens that the user and group id remain the same, the difference is that some extra groups are changing, apparently sufficiently enough to allow the execution of commands such as the downloaded binary. You can see that by yourself just by typing the `id` command in both cases (normal user or as administrator). 

By the way, if UAC is disabled, you execute silently a ton of commands without being warned anymore that you are using some admin rights to run them successfully. That should be the explanation why it works for some people and not for others.

**Comment by ewoudwerkman** [comment] 2017-01-11 12:45
It seems to me it has something to do with SDKMAN trying to repackage the downloaded file and trying to move the file to /cygdrive/c/temp/jdk while this folder does not exist (at least not on my machine). Does SDKman use the environment settings to determine the correct temp folder? Under cygwin it is /tmp, not /cygdrive/c/temp.

**Comment by ewoudwerkman** [comment] 2017-01-11 12:54
Have a look at the java_*_hook.sh script. C:\temp\jdk is hardcoded in there.

**Comment by ewoudwerkman** [comment] 2017-01-11 15:55
And yes, it seems you need to run this file as Administrator

**Comment by busches** [comment] 2017-03-01 19:07
Similar issues, even running as admin in Cygwin:

```
Repackaging java 6u45...
zip I/O error: No such file or directory
zip error: Could not create output file (/home/buschs1/.sdkman/tmp/Dm1krWm21MlhuLcj7rnbt4j1c8rbIXeM.zip)

Done repackaging...
mv: cannot stat '/home/buschs1/.sdkman/tmp/Dm1krWm21MlhuLcj7rnbt4j1c8rbIXeM.zip': No such file or directory
unzip:  cannot find or open /home/buschs1/.sdkman/archives/java-6u45.zip, /home/buschs1/.sdkman/archives/java-6u45.zip.zip or /home/buschs1/.sdkman/archives/java-6u45.zip.ZIP.
rm: cannot remove '/home/buschs1/.sdkman/archives/java-6u45.zip': No such file or directory
```

The expanded archive did exist at `.sdkman/tmp/out/jdk` which should have came from `'/home/buschs1/.sdkman/tmp/Dm1krWm21MlhuLcj7rnbt4j1c8rbIXeM.bin'` (notice the file extension is `.bin` instead of the `.zip`.

**Comment by marc0der** [comment] 2017-03-01 19:37
You should never run sdkman as admin, as this will mess with file permissions in your home folder. 

I think you might have an issue with the zip on your system. Can you please confirm that zip is provided by cygwin? 

I also think that this is local to your system as this is thoroughly tested to work on cygwin.

The post hook takes the bin file, extracts it using MSI, repackages as zip, stores the zip in archives and finally  explodes it under the candidates folder before adding it to the path. It clearly fails when packaging the zip.

**Comment by busches** [comment] 2017-03-01 20:03
You're right, I didn't have the `zip` utility installed. I see it's now required to install, but I don't remember seeing a prompt while upgrading. Thanks for the help.

**Comment by marc0der** [comment] 2017-03-01 21:42
Excellent. Glad it worked.

**Comment by pnelson5** [comment] 2017-03-03 19:38
I experienced the same issue.

Windows 7 64bit
Cygwin 2.877 (64bit)

```
$ sdk install java 7u80
Validate java 7u80 for CYGWIN_NT-6.1: valid
Validation URL: https://api.sdkman.io/2/candidates/validate/java/7u80/cygwin_nt-6.1
Get pre-installation hook: https://api.sdkman.io/2/hooks/pre/java/7u80/cygwin_nt-6.1
Copy remote pre-installation hook: /home/u6013973/.sdkman/tmp/hook_pre_java_7u80.sh
A pre-install hook was found for Java 7u80.

Oracle requires that you agree with the Oracle Binary Code License Agreement
prior to installation. The license agreement can be found at:

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

Do you agree to the terms of this agreement? (Y/n): Y

Dropped cookie...
Completed pre-installation hook...

Downloading: java 7u80

In progress...

######################################################################## 100.0%
Downloaded binary to: /home/u6013973/.sdkman/tmp/7RClWdK2AHi0CQAum8oxGwbKVnEglcWx.bin
Get post-installation hook: https://api.sdkman.io/2/hooks/post/java/7u80/cygwin_nt-6.1
Copy remote pre-installation hook: /home/u6013973/.sdkman/tmp/hook_pre_java_7u80.sh
A Cygwin post-install hook was found for Java 7u80.

Repackaging java 7u80...
-bash: /home/u6013973/.sdkman/tmp/7RClWdK2AHi0CQAum8oxGwbKVnEglcWx.bin: Permission denied
mv: cannot stat '/cygdrive/c/temp/jdk': No such file or directory

zip error: Nothing to do! (try: zip -qr /home/u6013973/.sdkman/tmp/7RClWdK2AHi0CQAum8oxGwbKVnEglcWx.zip . -i .)

Done repackaging...
Cleaning up cookie...
Processed binary as: /home/u6013973/.sdkman/tmp/7RClWdK2AHi0CQAum8oxGwbKVnEglcWx.zip
Completed post-installation hook...
mv: cannot stat '/home/u6013973/.sdkman/tmp/7RClWdK2AHi0CQAum8oxGwbKVnEglcWx.zip': No such file or directory
Moved to archive folder: /home/u6013973/.sdkman/archives/java-7u80.zip
unzip:  cannot find or open /home/u6013973/.sdkman/archives/java-7u80.zip, /home/u6013973/.sdkman/archives/java-7u80.zip.zip or /home/u6013973/.sdkman/archives/java-7u80.zip.ZIP.
rm: cannot remove '/home/u6013973/.sdkman/archives/java-7u80.zip': No such file or directory

Stop! The archive was corrupt and has been removed! Please try installing again.

```

I was able to workaround the issue by creating the folder C:/temp/jdk   and running the install again.

**Comment by rsrini7** [comment] 2017-03-19 11:11
I tried with msys2 with elevated mode (to resolve permission issue). Below is the issue.

Along with below console error, i got a popup error message too. 
Popup error Message: "there are errors in the following switches s:/"

$ sdk install java

Oracle requires that you agree with the Oracle Binary Code License Agreement
prior to installation. The license agreement can be found at:

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

Do you agree to the terms of this agreement? (Y/n): y


Downloading: java 8u121

In progress...

######################################################################## 100.0%

Repackaging java 8u121...
mv: cannot stat '/cygdrive/c/temp/jdk': No such file or directory

zip error: Nothing to do! (try: zip -qr /home/RSrini/.sdkman/tmp/W78xwPH685yypSpJFCkIdHsgi9STFFYO.zip . -i .)

Done repackaging...
mv: cannot stat '/home/RSrini/.sdkman/tmp/W78xwPH685yypSpJFCkIdHsgi9STFFYO.zip': No such file or directory
unzip:  cannot find or open /home/RSrini/.sdkman/archives/java-8u121.zip, /home/RSrini/.sdkman/archives/java-8u121.zip.zip or /home/RSrini/.sdkman/archives/java-8u121.zip.ZIP.
rm: cannot remove '/home/RSrini/.sdkman/archives/java-8u121.zip': No such file or directory

Stop! The archive was corrupt and has been removed! Please try installing again.

**Comment by jolarsso** [comment] 2017-03-21 14:23
I can confirm that sdkman needs the "zip" package installed for this process to work. I have installed sdkman on top of a babun-install of Cygwin and it seems that the "zip" package is not installed by default by babun.

In babun this was fixed by doing "pact install zip" and then re-running "sdk install java".

**Comment by marc0der** [comment] 2017-03-21 17:38
That's right. In fact, a new installation of sdkman mandates that you have
zip installed before proceeding with installation.

**Comment by jolarsso** [comment] 2017-03-22 11:14
I'm pretty sure I did not get any warnings or error when installing it on the babun 1.2.0 default-install of Cygwin (Windows 7 Professional x64). And if it really is mandated you should add that on the front page under the "Lightweight" heading since that currently says: "Written in bash and only requires curl and unzip to be present on your system. Even works with ZSH too.". 

Thanks for quick feedback though!

**Comment by marc0der** [comment] 2017-03-22 12:28
Noted, we will update this on the site. This is required due to the
post-processing and repackaging for Java.

**Comment by marc0der** [comment] 2017-03-26 10:33
@jolarsso Done.

**Comment by marc0der** [comment] 2017-03-28 06:59
@jbuhacoff  Can we close this issue?

**Comment by daithiscully** [comment] 2017-04-25 15:55
I am still receiving this issue:
Windows 10
Cygwin
Zip + unzip installed from the Cygwin packages
Uninstalled and reinstalled sdkman

When I run: `sdk install java 8u131`

I get the following:

`Oracle requires that you agree with the Oracle Binary Code License Agreement
prior to installation. The license agreement can be found at:

  http://www.oracle.com/technetwork/java/javase/terms/license/index.html

Do you agree to the terms of this agreement? (Y/n): y


Downloading: java 8u131

In progress...

######################################################################## 100.0%

Repackaging Java 8u131...
bash: /home/{USERNAME}/.sdkman/tmp/brgUnaur3882uTASrEWeHV1YzerQ7Sau.bin: Permission denied
mv: cannot stat '/cygdrive/c/temp/jdk': No such file or directory

zip error: Nothing to do! (try: zip -qr /home/{USERNAME}/.sdkman/tmp/brgUnaur3882uTASrEWeHV1YzerQ7Sau.zip . -i .)

Done repackaging...
mv: cannot stat '/home/{USERNAME}/.sdkman/tmp/brgUnaur3882uTASrEWeHV1YzerQ7Sau.zip': No such file or directory
unzip:  cannot find or open /home/{USERNAME}/.sdkman/archives/java-8u131.zip, /home/{USERNAME}/.sdkman/archives/java-8u131.zip.zip or /home/{USERNAME}/.sdkman/archives/java-8u131.zip.ZIP. rm: cannot remove '/home/{USERNAME}/.sdkman/archives/java-8u131.zip': No such file or directory

Stop! The archive was corrupt and has been removed! Please try installing again.`

Anybody find a solution for this yet?

**Comment by marc0der** [comment] 2017-04-25 16:18
Looking at your output I see a suspicious Permission Denied. Could that be
it?

**Comment by tkvw** [comment] 2017-04-25 19:02
Same error here (first attempt): 
![image](https://cloud.githubusercontent.com/assets/621098/25402809/36b877b4-29fa-11e7-88bb-2546b48d1cb3.png)

Second attempt (created c:/temp/jdk folder before install), permission denied: 
![image](https://cloud.githubusercontent.com/assets/621098/25402876/7c19d7c6-29fa-11e7-8325-e1d10e728cd0.png)

**Comment by busches** [comment] 2017-04-25 19:14
Permission denied is for trying to execute the `.bin` file, not the folder creation. Running as admin works, but as @marc0der mentions in other comments, running as admin can cause permissions issues. For installing Java, I've had to run as admin every time and have not ran into issues with Java, running as Admin all the time will result in permissions issues, e.g. maven.

**Comment by tkvw** [comment] 2017-04-25 19:27
Thanks, that did the trick.

**Comment by marc0der** [comment] 2017-04-25 20:22
Is there some way we can raise the permissions just for the execution of
the bin on cygwin? Something like sudo on Unix? I'd be happy to do
something like that in the post install hook where this execution takes
place.

**Comment by tkvw** [comment] 2017-04-25 21:01
Looks like ``` cygstart --action=runas n71ViS0iVgCglFwVLGqg9M26CDrlG6Z2.bin.exe /s INSTALLDIR=c:\\TEMP\\JDK ``` works

**Comment by marc0der** [comment] 2017-04-25 21:03
Cool, I could try adding that to the hook.

**Comment by tkvw** [comment] 2017-04-25 21:22
actually, it does not recognize .bin, so first move the bin to .exe
```
mv "$binary_input" "$binary_input.exe"
cygstart --action=runas n71ViS0iVgCglFwVLGqg9M26CDrlG6Z2.bin.exe /s INSTALLDIR=c:\\TEMP\\JDK
```
I have to check a clean console, because maybe it's just picking up previous set env variables

**Comment by tkvw** [comment] 2017-04-25 21:27
It does work with a fresh console, but it returns immediately. Adding -w to cygstart solves this. 
```
mv "$binary_input" "$binary_input.exe"
cygstart --action=runas -w n71ViS0iVgCglFwVLGqg9M26CDrlG6Z2.bin.exe /s INSTALLDIR=c:\\TEMP\\JDK
```

**Comment by marc0der** [comment] 2017-04-25 21:29
In case someone would like to raise a PR to fix this, the post install hook that does the work can be found here:
https://github.com/sdkman/sdkman-hooks/blob/master/app/views/java_cygwin_post.scala.txt

**Comment by marc0der** [comment] 2017-04-28 10:38
The only problem I have now is that this would automatically break on all systems using MYSYS as they don't have such a command. We probably need to find a solution that works for both of them.

**Comment by marc0der** [comment] 2017-04-28 11:50
I've done some further digging and have found that Cygwin and MYSYS emit different `uname` output as `CYGWIN_NT-6.3` and `MSYS_NT-6.3` respectively on my Vagrant box. When installing Java, we infer this all to be Windows 64, and thus treat it as Cygwin. This has worked fine up to now, although I think that the paths are now diverging. The right thing to do would be to treat these two as individual platforms.

I propose that we introduce a [new platform flag](https://github.com/sdkman/sdkman-cli/blob/master/src/main/bash/sdkman-init.sh#L45) on initialisation, then escalate privileges in the hook based on the platform flag. I will need some help from some knowledgeable MYSYS users who know how to escalate privileges on MYSYS. Any ideas?

**Comment by psramkumar** [comment] 2017-05-18 05:43
we should also consider GitBash for this installation process.
`MINGW64_NT-10.0` this is the uname value obtained from GitBash

**Comment by aadrian** [comment] 2017-05-18 05:55
+1 for GitBash.

The same way as Curl/Wget is a requirement for SDKMAM, "Git full install" (for GitBash) could be another one for Windows.

**Comment by psramkumar** [comment] 2017-05-18 11:42
Found one alternative for Time being,
zip JDK7 home folder as java-7u80.zip copy inside "SDKMAN_HOME/achives"
then run sdk install java 7u80

this time the installation will be success, since the binary is already downloaded in right place.

Similarly you can do the same for 8 and 9

hope this helps for now.

**Comment by marc0der** [comment] 2017-05-29 13:17
This problem automatically goes away now that Oracle JDKs have been pulled from SDKMAN. We will be rolling out all versions of OpenJDK available to us as [Zulu distributions](http://www.azul.com/downloads/zulu/zulu-windows/), which all come in zip format.

All the problems we were facing on Windows were due to the fact that we were having to execute a Windows installer in cygwin/msys. The executable MSI was the only format that Oracle provided for it's Windows users.

**Closed by marc0der** 2017-05-29 13:17 UTC
Labels: bug

**Comment by Najibsaurus** [comment] 2019-06-09 21:50
Try using git bash when installing SDKMAN and Java. It works for me.
