### ISSUE TITLE
Bug: [graills 6.2.1 unusable in ubuntu 24 wsl2]

### ISSUE THREAD

**Issue by joelBrun** [sdkman/sdkman-cli#1323] opened 2024-11-05 03:47 UTC
**Bug report**

The command `grails -version` returns an issue of buid executable architecture

**To reproduce**

sdk install java 11.0.25-tem
sdk install grails 6.2.1
grails -version

or 

sdk install java 17.0.13-tem
sdk install grails 6.2.1
grails -version

> The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].
> Please rebuild the executable with an appropriate setting of the -march option.

**System info**

- OS : Ubuntu-24.04 WSL2
- shell : bash 5.2.21
- sdk version:

> SDKMAN!
> script: 5.18.2
> native: 0.4.6

**Comment by linghengqian** [comment] 2024-11-05 15:17
- You seem to have opened the issue in the wrong place. Currently git only contains the frontend code for the sdkman client.

- The current issue should be opened at https://github.com/sdkman/sdkman-db-migrations , and resolving such an issue only requires a PR like https://github.com/sdkman/sdkman-db-migrations/pull/709 .

**Comment by marc0der** [comment] 2024-11-05 21:37
Hi @joelBrun,

This is not a bug or even an issue with SDKMAN but rather with Grails. All we do is download the Grails zip archive from their web page onto your machine and unpack it. We don't modify the SDK or even cache it. I suggest you raise an issue with the Grails team to see if they can help you.

Closing this issue in accordance with the contributing guidelines linked below.

**Closed by marc0der** 2024-11-05 21:37 UTC
