### ISSUE TITLE
File overwriting errors on shells with noclobber option

### ISSUE THREAD

**Issue by mfornos** [sdkman/sdkman-cli#263] opened 2014-03-01 20:00 UTC
If your shell has set the _noclobber_ option, you'll get errors after a default installation (v.1.3.13).

Running a shell session:
`~/.gvm/bin/gvm-init.sh:201: file exists: ~/.gvm/var/version`

And in update broadcast:
`__gvmtool_update_broadcast:9: file exists: ~/.gvm/var/broadcast`

To fix these you can use `>|` as redirect operator for overwriting files. Nevertheless, I'm not sure if the solution will work on all/most shells. As an example zsh supports both `>|` and `>!`. I'm sure that you'll find a proper solution, guys.

Cheers!

**Comment by marc0der** [comment] 2016-07-05 15:49
This could potentially fix issues that we've had with _prezto_, where it forces _noclobber_ to be set unconditionally.

**Comment by rgoldberg** [comment] 2020-04-22 05:14
This is a duplicate of #669, which was fixed by ##668.

Similar issues were noted in #484, and were fixed by #748.

This probably should be able to be closed.

**Closed** 2020-04-22 19:29 UTC
Labels: enhancement
