### ISSUE TITLE
Bug: sdkman installation fails

### ISSUE THREAD

**Issue by prabaharang** [sdkman/sdkman-cli#916] opened 2021-05-26 04:13 UTC
While installing `sdkman` inside a container getting below error.
```
/usr/local/sdkman/contrib/completion/bash/sdk: line 37: syntax error near unexpected token `<'
/usr/local/sdkman/contrib/completion/bash/sdk: line 37: `                       done < <(curl --silent "${SDKMAN_CANDIDATES_API}/candidates/all")'
```

**To reproduce**
```
FROM amazonlinux:2.0.20210421.0
RUN yum -y -q update && yum install -y -q zip unzip
RUN export SDKMAN_DIR="/usr/local/sdkman" && curl -s "https://get.sdkman.io" | bash \
	&& source "/usr/local/sdkman/bin/sdkman-init.sh" 
```

The same `Dockerfile` was worked till v5.11.4. Please suggest.

**Comment by KornKalle** [comment] 2021-05-26 08:46
Can confirm the same behavior occuring since today

**Comment by KornKalle** [comment] 2021-05-26 09:48
issue got fixed by @marc0der 
Thank you!

**Comment by marc0der** [comment] 2021-05-26 16:37
I've now put an [additional safeguard](https://github.com/sdkman/sdkman-cli/commit/290365a87577937fb6b329f93b733dafcece3daf) in the code that will always prevent completion scripts being sourced in shells other than zsh or bash.

**Comment by marc0der** [comment] 2021-06-16 22:10
@prabaharang just wanted to check if you are seeing this crop up again or if it is working fine now.

**Comment by KornKalle** [comment] 2021-06-17 10:47
I can confirm that it is happening again in our build environment

**Comment by prabaharang** [comment] 2021-06-18 06:12
@marc0der Yes, still issue happens. When I try to build the image using the above-mentioned `Dockerfile` script, I'm getting the below error.
```
/usr/local/sdkman/contrib/completion/bash/sdk: line 37: syntax error near unexpected token `<'
/usr/local/sdkman/contrib/completion/bash/sdk: line 37: `                       done < <(curl --silent "${SDKMAN_CANDIDATES_API}/candidates/all")'
```

**Comment by marc0der** [comment] 2021-06-22 08:55
Thanks, both. We have a PR that should hopefully go in soon that will fix this problem.

**Comment by marc0der** [comment] 2021-07-04 15:57
@prabaharang @KornKalle On closer inspection, it looks like a [PR was already merged](https://github.com/sdkman/sdkman-cli/commit/55749a4a400347ac5a405188f36ef70af423f281) that supposedly fixes this. It is currently sitting in the beta channel. Can someone confirm that this is working before I perform a stable release?

**Comment by prabaharang** [comment] 2021-07-06 12:20
@marc0der I'm not sure how I could point to the beta channel. I performed the steps below:

1. Copied the script from https://get.sdkman.io/ and placed it in my Docker client’s current directory.
2. Changed the `sdkman_beta_channel` value to `true` --> `echo "sdkman_beta_channel=true" >> "$sdkman_config_file"`
3. Ran the below Dockerfile and still getting an error.
```
FROM amazonlinux:2.0.20210421.0
RUN yum -y -q update && yum install -y -q zip unzip
COPY ./sdkman-int.sh .
RUN export SDKMAN_DIR="/usr/local/sdkman" && cat sdkman-int.sh | bash && source "/usr/local/sdkman/bin/sdkman-init.sh"
```

> /usr/local/sdkman/contrib/completion/bash/sdk: line 37: syntax error near unexpected token `<'
/usr/local/sdkman/contrib/completion/bash/sdk: line 37: `                       done < <(curl --silent "${SDKMAN_CANDIDATES_API}/candidates/all")'

Maybe I'm missing something.

**Comment by marc0der** [comment] 2021-07-09 13:28
Thanks for trying @prabaharang, it is a tricky thing to test.
I'll spend some time to see if I can replicate it locally and apply the fix.

**Comment by valsr** [comment] 2021-07-18 17:29
I ran into a second instance of this issue -> line 77 has the same `done < <(curl..` problem. Fixed it by applying similar changes as in the PR

**Comment by marc0der** [comment] 2021-07-18 18:23
@valsr if you have a fix, feel free to raise a PR. I'd be happy to merge.

**Comment by marc0der** [comment] 2021-08-16 10:40
I've tested this again today with the snippet that @prabaharang posted, and it now works fine for me.

@valsr If you still see this issue on your side, please feel free to raise a PR to fix it.

**Closed by marc0der** 2021-08-16 10:40 UTC
Labels: bug
