### ISSUE TITLE
Bug: sdk list java produces HTML not found response

### ISSUE THREAD

**Issue by jameskleeh** [sdkman/sdkman-cli#811] opened 2020-10-22 18:42 UTC
**Bug report**
`sdk list java` produces an HTML response

**To reproduce**
```
log $ sdk list java
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Not Found</title>
        
<style  type="text/css">
            html, body, pre {
                margin: 0;
                padding: 0;
                font-family: Monaco, 'Lucida Console', monospace;
                background: #ECECEC;
            }
            h1 {
                margin: 0;
                background: #AD632A;
                padding: 20px 45px;
                color: #fff;
                text-shadow: 1px 1px 1px rgba(0,0,0,.3);
                border-bottom: 1px solid #9F5805;
                font-size: 28px;
            }
            p#detail {
                margin: 0;
                padding: 15px 45px;
                background: #F6A960;
                border-top: 4px solid #D29052;
                color: #733512;
                text-shadow: 1px 1px 1px rgba(255,255,255,.3);
                font-size: 14px;
                border-bottom: 1px solid #BA7F5B;
            }
        </style>
    </head>
    <body>
        <h1>Not Found</h1>

        <p id="detail">
            For request 'GET /candidates/java/Darwin/versions/list?current=&amp;installed='
        </p>

    </body>
</html>
```

**System info**
- macOS
- GNU bash, version 5.0.7(1)-release (x86_64-apple-darwin18.5.0)
- 5.9.1+575

**Comment by jameskleeh** [comment] 2020-10-22 18:59
Its 17 minutes later and I can no longer reproduce

**Comment by chrix75** [comment] 2020-10-25 09:10
Hi, 
I've just tried and I got this error in HTML:

```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.19.1</center>
</body>
</html>
```

**Comment by marc0der** [comment] 2020-10-25 09:52
Hi @jameskleeh, we've had some abuse of our APIs lately. I've put some IP blocking in place so this should solve the problem. Please let me know if the issue persists.

**Comment by chrix75** [comment] 2020-10-25 12:55
> Hi @jameskleeh, we've had some abuse of our APIs lately. I've put some IP blocking in place so this should solve the problem. Please let me know if the issue persists.

For me, the problem is still here :(

**Comment by marc0der** [comment] 2020-10-25 13:10
@chrix75 sounds like you might be having a different issue. You are getting a 404 from nginx, pointing to a potentially outdated version of sdkman. Feel free to ask on Slack #user-issues, one of us would be happy to help if your problem persists.

**Comment by chrix75** [comment] 2020-10-25 17:39
@marc0der the selfupdate force didn't work. So, I've tried a new installation of Sdkman and now all is working. Thanks and sorry for the mistakes.

**Comment by marc0der** [comment] 2020-10-25 17:42
Not at all! It's my fault for not keeping the legacy endpoints alive long enough. I'm glad you got it sorted.

**Comment by marc0der** [comment] 2020-10-25 17:42
@jameskleeh mind if we close this issue now?

**Comment by jameskleeh** [comment] 2020-10-25 19:16
Sure thing

**Closed** 2020-10-25 19:17 UTC
Labels: bug
