### ISSUE TITLE
sdkman-init.sh not able to run from .profile (use .bashrc) for  Ubuntu  initd

### ISSUE THREAD

**Issue by aplatypus** [sdkman/sdkman-cli#568] opened 2017-04-27 12:54 UTC
Hi.  We are pretty sure this applies to all Ubuntu and derived distributions using a GUI desktop.  After some quirky experiences with the `sdkman-init.sh` at start-up I found myself needing to manually run the prescribed lines of initialisation on the terminal console: 
```
#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
[[ -s "/home/dudette/.sdkman/bin/sdkman-init.sh" ]] && source "/home/dudette/.sdkman/bin/sdkman-init.sh"
```
... if ever I wanted to use sdkman.  These lines are commonly added to the end of the .profile or your bashrc file.  First the good news, then the suggested root-cause remedy.

###  _good news_
The good news is that _when_ these two lines are executed from a `.bashrc` file, the sdkman initialises 100%.  So your console builds and such work well.  Even with that fixed, I found I was still having bother with IDE-s: Netbeasn and IDEA until I changed the desktop short-cut to start a bash script which ran  `sdkman-init.sh` first and then the IDE.  So that approach also works.

###  _analysis_
What does NOT work is adding the  `sdkman-init.sh` to a `~/.profile` file that is run as part of the login on Ubuntu.  We tested this on Bodhi, Linux Mint and Ubuntu.  The problem is that the 

- initialisation,  `initd` and login and `/etc/profile.d` run under the **`dash`** shell, **_not_** `**bash`**
For instance under the X-Windows start-up I get this message in **`~/.xsession-errors`**:
```
/etc/mdm/Xsession: Beginning session setup...
/etc/mdm/Xsession: 78: /home/aplatypus/.profile: [[: not found
    * ERROR:  Cannot see $SDKMAN_DIR/bin/sdkman-init.sh
```
I added the log messages showing what is running.  That message come at the end of the `~/.profile` script.  The reasons are that

1.  `[[ ... ]]` is a `bash` feature and  `dash` doesn't understand the `[[` construct: "[[: not found"
1.  `dash` doesn't have `source` and you need to use **`.`**

I changed a test `.profile` file a little to step-past this small problem.  This is what happens if you fire-up `dash` in your favourite `term` program and run the `sdkman-init.sh` ...
```
$ dash
$ pwd
/home/platypus
$     if  [ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ] ;    
    then
        source "$SDKMAN_DIR/bin/sdkman-init.sh"
    else
        echo "    * ERROR:  Cannot see \$SDKMAN_DIR/bin/sdkman-init.sh"
    fi
> > > > > dash: 8: source: not found
$ 
$ 
$ 
$     if  [ -s "$SDKMAN_DIR/bin/sdkman-init.sh" ] ;    
    then
        . "$SDKMAN_DIR/bin/sdkman-init.sh"
    else
        echo "    * ERROR:  Cannot see \$SDKMAN_DIR/bin/sdkman-init.sh"
    fi
> > > > > dash: 20: /home/platypus/.sdkman/bin/sdkman-init.sh: [[: not found
dash: 22: /home/platypus/.sdkman/bin/sdkman-init.sh: [[: not found
dash: 68: /home/platypus/.sdkman/bin/sdkman-init.sh: [[: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 76: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 89: /home/platypus/.sdkman/bin/sdkman-init.sh: source: not found
dash: 93: /home/platypus/.sdkman/bin/sdkman-init.sh: [[: not found
dash: 98: /home/platypus/.sdkman/bin/sdkman-init.sh: [[: not found
dash: 99: /home/platypus/.sdkman/bin/sdkman-init.sh: [[: not found
dash: 103: /home/platypus/.sdkman/bin/sdkman-init.sh: [[: not found
dash: 108: /home/platypus/.sdkman/bin/sdkman-init.sh: __sdkman_echo_debug: not found
dash: 109: /home/platypus/.sdkman/bin/sdkman-init.sh: __sdkman_secure_curl_with_timeouts: not found
dash: 110: /home/platypus/.sdkman/bin/sdkman-init.sh: __sdkman_echo_debug: not found
dash: 112: /home/platypus/.sdkman/bin/sdkman-init.sh: [[: not found
dash: 121: /home/platypus/.sdkman/bin/sdkman-init.sh: [[: not found
dash: 126: /home/platypus/.sdkman/bin/sdkman-init.sh: __sdkman_echo_debug: not found
dash: 127: /home/platypus/.sdkman/bin/sdkman-init.sh: [[: not found
dash: 131: /home/platypus/.sdkman/bin/sdkman-init.sh: __sdkman_echo_debug: not found
dash: 135: /home/platypus/.sdkman/bin/sdkman-init.sh: __sdkman_secure_curl_with_timeouts: not found
dash: 136: /home/platypus/.sdkman/bin/sdkman-init.sh: [[: not found
dash: 136: /home/platypus/.sdkman/bin/sdkman-init.sh: -n: not found
dash: 141: /home/platypus/.sdkman/bin/sdkman-init.sh: __sdkman_echo_debug: not found
```
If the script is likely to run under the initd (and upstart too) regime(s) using the default shell, viz. `dash` -- Then the shell script needs to avoid the `bash` specific commands such as: `[[`, `source`, and potentially others.  

###  _remedy_
As I say, I've found some helpful work arounds  _before_ I accidentally uncovered the lack of `dash` compatibility while trying to debug an issue with start-up.  

I strongly suggest the `sdkman-init.sh` and underlying scripts are revised to be `dash` compatible.  I can't really say what the scope is -- There's at least 39 x lines above that would need modification.

Don't use
1.  `[[` for `test`
1.  use  **`.`** (dot) over `source` (bash only)

I am not sure what happened to: ` __sdkman_echo_debug` in the test.  Perhaps that's a function(??)

###  _why be_ `dash`-_ing?_
Like me you may think the `sdkman-init.sh` only needs to run for console shells.  It is probably fair to document how to write a little `sdkman-init.sh` preamble in a shell script to fire-up Netbeans and IDEA so you can use the sdkman managed Gradle, Groovy, Java, Kotlin or Maven of your choice ...  May be not _fair_ but not unreasonable.

I didn't think that way for long.  Several things go wrong from time to time, and now I can see that it is probably also due to bits of `sdkman environment` not being as I had presumed.  A failure in the `xsession` start-up is virtually invisible until you look a the errors file.  So  changing scripts will probably clean-up some other bugs  or things closed-off as "_unable to reproduce_".  For example, this  issues look like  the same cause:
- issue #532 

The thing is, _could_ I run a java or a groovy script under sdkman auspices at system start-up -- That is before my desktop begins?  Given the straightforward nature of what's required; I say it is worth while fixing this bug if only to have one-less thing that needs checking when _things_ don't work  #OK. 

Finally for people with the `sdkman-init.sh` in their `.profile` -- I recommend moving it to the `.bashrc` file at least until this is fixed.

**Comment by marc0der** [comment] 2017-07-26 07:49
Sorry for the late reply on your issue. Thanks for the very thorough investigation and analysis of the root cause of this problem. This problem has plagued many Ubuntu users (including all derivatives) for some time.

With regards to making SDKMAN dash compliant, I don't think this will ever happen. We are dedicated to support bash and ZSH at this point in time. Supporting all other flavours of shells would cause a combinatorial explosion, and make the code brittle.

I'm always in favour of the simplest solution, and in this case it's the one that you allude to at the end of your post: simply remove initialisation of SDKMAN from the `.profile` and make sure that it appears in the `.bashrc` and/or `.zshrc`.

I'll be making this change shortly in the install script, so this will be fixed in all new installations going forward. Worth mentioning though that those who have already installed SDKMAN on an Ubuntu based system should remove these lines from their `.profile`.

**Comment by marc0der** [comment] 2017-07-27 08:00
I've now updated the installation script to do the following:

* create a new `.bashrc` if it does not exist
* add the initialisation snippet to the end of `.bashrc`
* create a new `.zshrc` if it does not exist
* add the initialisation snippet to the end of `.zshrc`

We no longer touch the `.profile` or `.bash_profile` or `.bash_login` files.

This should fix all weird behaviour on all new installations. If having sdkman available in a login shell, users can manually add the snippet to their profiles. For the sake of completeness, here is the snippet code that needs to be added to the end of the `.profile` if required:

    #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
    [[ -s "/home/marco/.sdkman/bin/sdkman-init.sh" ]] && source "/home/marco/.sdkman/bin/sdkman-init.sh"

The above snippet can be dummed down to work with dash if required on Ubuntu derivatives.

**Closed** 2017-07-27 08:02 UTC

**Comment by aplatypus** [comment] 2017-07-27 12:33
Still won't work with the ash shell -- Which more or less runs everything BEFORE the command shell kicks off.

**Comment by marc0der** [comment] 2017-07-27 15:50
Unfortunately we simply can't port the entire CLI to be dash compliant. We only support bash and ZSH as stated on our home page. This is the best compromise we can make for now.

**Comment by aplatypus** [comment] 2017-08-04 14:53
That decision eliminates every GUI tool running on X.  The x-server start-up comes before the bash shell kicks-in

 ... So it will be a good idea to document how people can add a script to pre-run the sdkman init script prior to executing your favourite tool, GUI app or game.  For instance I have a little bash script to kick-off IDEA and I added the sdkman start-up to my Netbeans script (bash).   These are programming tools (_but_) 

The thing that really bothered me was I can't execute simple stuff that needs (_say_) Groovy or Kotlin-script with a GUI app without wrapping the app's start-up script / command -- _Whatever_.

I doubt for instance that a Tomcat server can support a 

The actual surface-area for the task support Dash seems feasible if you can consider a stepped-migration strategy.  The difficulty seems to be the lack of "`source`" facility -- As a first step it would seem reasonable to ask for a source or in-line facility in dash... (_??_).  Source commands can always be replaced by a (so called) script compiler.  I did something for SQL to make db migrations easier to maintain.  Those are hard-options.  One ought to discover why Dash doesn't have a "`source`" operation.

As far as the output for  sdkman  -- Dash supports the `export` command.   

I guess Dash support, while feasible/practical -- Is a choice of Scope.  Does SDKMAN purport to support Linux applications such as:

 - GUI applications  /  **NO**
 - Webservers (Tomcat, NixGen, Grails, Jetty, ApacheD, ...)   /  **NO**
 - Linux services implemented with: Java, Groovy, JRuby, JPython, Kotlin, Scala, ...   /  **NO**
 - Boot time Groovy, Java, Kotlin, etc. programs or star-scripts, other --   /  **NO**
 - init.d   /  **NO**
 - web-server based appls like XWiki. Spago, etc ...   /  **NO**
 - 

For me, I can identify pathways .. . I haven't (of course) hacked the source code.  That said, the response is _literally_ a "_prefer not to_" support Linux start-up.  SDKMAN _chooses_ to restrict itself to user-level shell exec-s.  As there are actual, practical approaches to give Dash equal footing.

Rhetoric aside, it just seems to me that Detouring around Dash creates a big Linux and derived systems NO-GO area.  A "_Hack-around-an-Elephant-in-the -Room-zone_".  I'm pretty sure Linux is here to stay and I'm in agreement with people wanting to basic tool like Dash, Ash, etc for boot and start-up actions.
