### ISSUE TITLE
Installed JDK in Mac, But can show it with system command `/usr/libexec/java_home`

### ISSUE THREAD

**Issue by qiunet** [sdkman/sdkman-cli#638] opened 2018-04-24 12:45 UTC
We require a conversation to take place in the appropriate Gitter Room before raising a new Github Issue. Please note that **issues will be closed immediately if prior discussion did not take place**. We need to do this to help manage the quality and validity of Issues raised on this project.

Please tick one:
- [ ] this is a new Feature Request, a conversation was started in the [Gitter CLI Development Room](https://gitter.im/sdkman/cli-dev).
- [x] this is a new Bug Report or Issue, a conversation was started in [Gitter User Issues Room](https://gitter.im/sdkman/user-issues).

Please explain the Issue / Feature Request here:
Hi 
I was installed JDK on MacOs, But can show it with command `/usr/libexec/java_home -X`. 
And Eclipse can not run with this JDK. It is need install another one. 
It is anyway to fix this?  Thanks.
![image](https://user-images.githubusercontent.com/754437/39187595-4e4bd07c-4800-11e8-88d3-dfcd92112dbd.png)

**Comment by marc0der** [comment] 2018-04-24 17:02
Please follow the contributor guidelines before opening an issue. That means that you do what the tick box above says: start a discussion on our gitter user issues chat where we will answer your questions.

This is not a bug but a problem with your local environment so closing the issue now.

**Closed by marc0der** 2018-04-24 17:02 UTC
