### ISSUE TITLE
Bug: Unable to install java

### ISSUE THREAD

**Issue by tdahmez** [sdkman/sdkman-cli#1174] opened 2023-02-14 10:57 UTC
**Bug report**
Version SDKMAN 5.16.1 is broken.
Makes any command respond with 'Stop! java is not a valid candidate.'

Uninstalling and reinstalling sdkman does not solve the problem.

**To reproduce**
terminal command : sdk install java

**System info**
Please add relevant information about your system:
- Mac 13.2
- GNU bash, version 3.2.57(1)-release (arm64-apple-darwin22)
- SDKMAN!
script: 5.16.1
native: 0.1.0

**Comment by maxstreese** [comment] 2023-02-14 11:18
`sdk install java` is not a valid candidate though? You need to specify which of the available Java candidates you want to install. Do `sdk list java` and you will get back the possible candidates.

**Comment by martinvisser** [comment] 2023-02-14 11:48
Seems like a duplicate of https://github.com/sdkman/sdkman-cli/issues/1173

**Closed** 2023-02-14 11:59 UTC
Labels: bug

**Comment by manish2aug** [comment] 2023-02-14 13:34
No, it's not duplicate, the candidate api service is up but the java candidate is still missing and on install or list it gives the same error

![image](https://user-images.githubusercontent.com/17476238/218753734-b6f3fac8-4946-45c9-a941-5583a1bfd87b.png)

**Comment by marc0der** [comment] 2023-02-14 13:36
@manish2aug Just run `sdk update` as mentioned in our community slack.

**Comment by manish2aug** [comment] 2023-02-14 13:46
Thanks, it's sorted, running the same command in a new terminal shows the candidates
