### ISSUE TITLE
Bug: Installation script fails with newline error

### ISSUE THREAD

**Issue by dheerajchand** [sdkman/sdkman-cli#1293] opened 2024-05-14 15:12 UTC
**Bug report**
1. Opened terminal on M1 MBP, `zsh`
2. Copied command from installation screen into terminal
3. Executed
4. Error obtained

```
 ~  curl -s "https://get.sdkman.io" | bash                 ✔  108  10:09:00
bash: line 1: syntax error near unexpected token `newline'
bash: line 1: `<!--# Id: internetaccess.html 285144 2021-06-16 05:02:06Z szhang -->'
 ~  zsh --version                                      0|2 ↵  109  10:09:29
zsh 5.9 (x86_64-apple-darwin23.0)
 ~ 
```
**To reproduce**

1. Open terminal
2.  Paste command
3.  Execute

**System info**

1. M1 MBP
2. ```zsh 5.9 (x86_64-apple-darwin23.0```

**Comment by helpermethod** [comment] 2024-05-14 15:32
Hi @dheerajchand, do you have some security software like ZScaler installed on your system?

**Comment by dheerajchand** [comment] 2024-05-15 16:16
Unfortunately, yes. It is a work laptop.

**Comment by marc0der** [comment] 2024-05-15 22:04
In that case I'd say it's not a bug with our software. Closing this for now.

**Closed by marc0der** 2024-05-15 22:04 UTC
Labels: bug

**Comment by dheerajchand** [comment] 2024-05-16 13:58
Thanks for the insight! Is there any suggested workaround?

**Comment by helpermethod** [comment] 2024-05-16 14:08
> Thanks for the insight! Is there any suggested workaround?
> 

Not that I am aware of.

**Comment by marc0der** [comment] 2024-05-16 16:21
You'll be faced with this issue whenever you try to use curl, not just when using SDKMAN.
