### ISSUE TITLE
Installing failed for springboot on cygwin

### ISSUE THREAD

**Issue by mahaoboy** [sdkman/sdkman-cli#701] opened 2019-06-21 01:50 UTC
I can not install springboot and any other package supplied by sdkman;
Here is the print log:
`
cdmahao@CDYJY-455F9FF1 ~
$ sdk install springboot

Downloading: springboot 2.1.6.RELEASE

In progress...

Warning: Failed to create the file
Warning: /home/cdmahao/.sdkman/tmp/WTHWg8hMF2RKVKrsVUT2cAiJxDHDSYv4.bin: No
Warning: such file or directory
                                                                           0.0%
curl: (23) Failed writing body (0 != 606)
mv: '/home/cdmahao/.sdkman/tmp/WTHWg8hMF2RKVKrsVUT2cAiJxDHDSYv4.bin' (stat): No such file or directory
`
Can you help on this?

**Comment by marc0der** [comment] 2019-06-21 05:25
Please follow the guidelines before opening new issues here. We can help with user issues on the appropriate slack channel.

Closing this as it's not a bug.

**Closed by marc0der** 2019-06-21 05:25 UTC

**Comment by mahaoboy** [comment] 2019-06-21 06:09
Ok, Thanks for your reminding.

**Comment by mahaoboy** [comment] 2019-06-21 06:17
> Please follow the guidelines before opening new issues here. We can help with user issues on the appropriate slack channel.
> 
> Closing this as it's not a bug.

I can not join following channels at all; Is there anyway I can get the channel invitation link?
- [Slack CLI Development Channel](https://sdkman.slack.com/app_redirect?channel=user-issues).
- [Slack User Issues Channel](https://sdkman.slack.com/app_redirect?channel=cli-development).

**Comment by marc0der** [comment] 2019-06-21 06:20
I'll make this a bit clearer on the template, but you can sign up very easily by going to https://slack.sdkman.io

**Comment by mahaoboy** [comment] 2019-06-21 06:23
> I'll make this a bit clearer on the template, but you can sign up very easily by going to https://slack.sdkman.io

Thanks a lot. :-)
BR

**Comment by marc0der** [comment] 2019-06-21 06:37
I've updated all templates so slack access should be a bit easier now.

**Comment by mahaoboy** [comment] 2019-06-21 06:46
> I've updated all templates so slack access should be a bit easier now.

Appreciate that, but I found the links of the slack channels are not corresponding to the link text in the templates;

**Comment by marc0der** [comment] 2019-06-21 06:49
Will take a closer look thanks.

**Comment by mahaoboy** [comment] 2019-06-21 07:03
> Will take a closer look thanks.

:-)

**Comment by laoduDYM** [comment] 2019-06-24 02:57
> > Will take a closer look thanks.
> 
> :-)
Hello, have you found a solution? I have the same problem.

**Comment by seanf** [comment] 2020-11-21 13:06
The short version of the solution is this: 

**Install Cygwin's version of `curl`.** There's a copy in `C:\Windows\System32\curl.exe` but it doesn't work for SDKMAN!



Since the record [in Slack](https://sdkman.slack.com/archives/CJTNQA94M/p1561869409005300) may not be permanent, and this page is easier to find with a search engine, I'll copy here what I found in Slack (the same or very similar issue). 

Thanks for the solution @hantsy!

Hantsy on June 30th, 2019:
> I am trying to install spring boot by Sdk, but failed.
> I am using Windows 10 v1903, AdoptOpenJdk 11.0.3, Cygwin with zip/unzip installed.
> When I ran the sdk install springboot in Cygwin terminal.
> And got the following message.
> ```
>  sdk install springboot
> 
> Downloading: springboot 2.1.6.RELEASE
> 
> In progress...
> 
> Warning: Failed to create the file
> Warning: /home/hantsy/.sdkman/tmp/nVfHhQzE6lm4ddKPyGigGxFOJhOw1cYB.bin: No
> Warning: such file or directory
>                                                                            0.0%
> curl: (23) Failed writing body (0 != 1870)
> mv: cannot stat '/home/hantsy/.sdkman/tmp/nVfHhQzE6lm4ddKPyGigGxFOJhOw1cYB.bin': No such file or directory
> ```
> Not sure where is wrong. Any suggestions to overcome this barrier?
> Thanks
> 
> When I tried to install Java.    
> ```
> sdk install java
> 
> Downloading: java 11.0.3-zulu
> 
> In progress...
> 
> 
> curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092013) - The revocation function was unable  check revocation because the revocation server was offline.
> mv: cannot stat '/home/hantsy/.sdkman/tmp/Np5CyjTEy7b8OpYjcFwOVFknAPIrqldI.bin': No such file or directory
> ```
> 
> Got resolved by installing curl into Cygwin instead of the system existed one.
> It seems the Windows built-in curl is buggy.
> Which cause the problems

See also https://github.com/sdkman/sdkman-cli/issues/703
