### ISSUE TITLE
Bug: Tests on Mac OSX are not running anymore

### ISSUE THREAD

**Issue by helpermethod** [sdkman/sdkman-cli#873] opened 2021-02-15 11:41 UTC
**Bug report**
After changes to the platform inference, multiple tests stopped working on Mac OSX.

**To reproduce**

**System info**
- macOS Catalina
-GNU bash, Version 5.0.17(1)-release (x86_64-apple-darwin18.7.0)
- SDKMAN master+647

There seem to be multiple problems which lead to the tests failing. 

1. `UnixUtils.groovy` infers the wrong platform

UnixUtils.groovy expects `System.getProperty("os.name")` to resolve to `Darwin`, while it actually resolves to `Mac OS X`.

```
jshell> System.getProperty("os.name")
$1 ==> "Mac OS X"
```

Interestingly, `uname -s` returns `Darwin` on my machine 😕. 

2. `UnameStub` by default uses platform/kernel `Linux` and machine `X86_64`. This causes problems on Mac OSX, because SDKMAN! then chooses a non-compatible version of `sed`.

This could probably be fixed by replacing the platform-dependent code with shell builtins (this would also slightly improve performance, as less processes need to be forked).

**Comment by marc0der** [comment] 2021-02-21 15:36
@helpermethod I've pushed a fix but having a difficult time testing this with virtualbox. Please let me know if the problem is resolved now.

**Comment by helpermethod** [comment] 2021-02-21 15:40
I'll give it a go this evening!

**Closed** 2021-03-30 21:47 UTC
Labels: bug
