### ISSUE TITLE
Can't install candidates (like grails) with zsh: can't create local array elements

### ISSUE THREAD

**Issue by jbounlip** [sdkman/sdkman-cli#326] opened 2015-04-05 01:52 UTC
After installing gvm through this script (_curl -s get.gvmtool.net | bash_), I've tried to install grails after sourcing _gvm-init.sh_ :

    $ gvm install grails
    gvm:local:70: ^[[01;31m^[[Kgrails^[[m^[[K: can't create local array elements

Unfortunately, _only Bash has declare, the kshes and zsh have typeset... _ (http://stackoverflow.com/questions/10194861/bash-zsh-declare-oh-my).

I had to switch back to bash shell to use gvm.

**Comment by marcoVermeulen** [comment] 2015-04-07 14:17
That's very odd, since I (as well as many others) are using zsh and not experiencing any problems at all. Could you give more details please?

**Comment by marcoVermeulen** [comment] 2015-08-28 11:45
Closing this issue after no reply received.

**Comment by msiler** [comment] 2015-10-27 19:59
I have this exact same issue. I'm using zsh. I installed sdkman via 'curl -s get.sdkman.io | bash'. I then opened a new terminal and ran sdk version. It showed version 3.2.3. I then did 'sdk install grails' and got the exact same error message as the OP. What extra details would you like?

**Comment by marc0der** [comment] 2015-10-27 20:02
Could you please give me all details about your system? Platform, zsh version, ohmyzsh/prezto.

Do you see the same when installing other candidates, or only grails?

**Comment by msiler** [comment] 2015-10-27 20:11
uname -a:
Linux gauss 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

zsh --version:
zsh 5.0.2 (x86_64-pc-linux-gnu)

Using ohmyzsh.

java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

I just tried `sdk install gaiden` and got the exact same error, but with grails replaced with gaiden.

**Comment by marc0der** [comment] 2015-10-27 21:55
Thanks for that. When running the same commands on my machine, I get the following result:

    $ uname -a
      Linux schrodinger 3.19.0-31-generic #36-Ubuntu SMP Wed Oct 7 15:04:02 UTC 2015 x86_64 x86_64 GNU/Linux
    $ zsh --version
      zsh 5.0.7 (x86_64-pc-linux-gnu)

My guess is that you are running an outdated system. My guess would further be that the problem is caused by version 5.0.2 of zsh. Try upgrading your system and getting a later version of zsh and all problems should go away.

**Comment by msiler** [comment] 2015-10-28 13:56
I updated zsh to version 5.1.1, but still get the exact same error. I tried on a different system which had zsh 5.0.7 on it already and everything worked fine. I don't have that system available right now, otherwise I'd give other system info, but I believe it is running a more recent version of Ubuntu. So perhaps the problem is old versions, just not of zsh.

**Comment by marc0der** [comment] 2015-10-28 14:10
Good to know thanks. I'll keep this issue open until you have further news.

**Comment by msiler** [comment] 2016-03-07 21:34
I recently came back to this and noticed that if I switch into bash from zsh, then everything runs fine. So maybe you are right that this is an issue with zsh.

**Closed** 2016-07-05 15:08 UTC
